
package Forms;

import Resources.LocalizationUtil;
import Users.User;
import java.awt.Cursor;
import java.awt.event.MouseEvent;
import javax.swing.JMenu;

/**
 *
 * @author ANI
 */

public class AdminHome extends UserHome {
    WelcomeScreen previous = null;
    User player = null;
    JMenu mnuAdminOptions = new JMenu();
    String language = "";
    boolean isHebrew = false;
    
    /**
     * Creates new form AdminHome
     */
    public AdminHome(){}
    
     public AdminHome(User player,WelcomeScreen previous) {
       super(player, previous);
       initComponents();
       initMyComponents();
    }
     
     public AdminHome(User player,WelcomeScreen previous,String lang) {
         super(player,previous,lang);
         initComponents();
         initMyComponents();
         this.language = lang;
        if (lang.equals("iw"))
        {
             LocalizationUtil.localizedResourceBundle =
                     LocalizationUtil.getBundleHomeIW();
             mnuAdminOptions.setText
        (LocalizationUtil.localizedResourceBundle.getString("mnuAdminOptions"));
            super.changeToHebrew();
        }
    }
     private void initMyComponents()
     {
        addListeners(); 
        mnuAdminOptions.setText("Admin Options");   
        mnuAdminOptions.setCursor
        (Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        mnuAdminOptions.setToolTipText("Click for more options");
        menuBar.add(mnuAdminOptions);
        setJMenuBar(menuBar);
     }
     
     private void addListeners()
     {
           mnuAdminOptions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuAdminOptionsMouseClicked(evt);
            }
        });
         
     }
     
     private void mnuAdminOptionsMouseClicked(MouseEvent evt) {  
         this.setVisible(false);
         ListOfUsers listOfUsers;
         if (this.language.equals("iw"))
         {
          listOfUsers = new ListOfUsers(this,this.language);
         }
         else{
            listOfUsers = new ListOfUsers(this); 
         }
         listOfUsers.setVisible(true);
     }
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 673, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(632, 435));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
